spring:
  datasource:
    url:
      jdbc:h2:mem:test
    username:
      username
    password:
      password
  jpa:
    show-sql: true #pokazanie wykonywanych zapytan sql w konsoli
    defer-datasource-initialization: true #opoznienie wykonania skryptu z pliku data.sql

